### ISSUE TITLE
URL 配置错误

### ISSUE THREAD

**Issue by yzqzss** [MrWillCom/MrWillCom.github.io#3]
https://github.com/MrWillCom/MrWillCom.github.io/blob/d271570e691bde348eeeb6ed8df5723227d04370/_config.yml#L16

[Feed](https://mrwillcom.github.io/atom.xml)里输出的链接全指向了 https://mrwillcom.vercel.app/  ，如：https://mrwillcom.vercel.app/2021/08/14/Encrypt-it-on-Your-Own/ ，该文章地址无法访问。

建议改为 https://blog.mrwillcom.vercel.app/ 或 https://mrwillcom.github.io/

**Comment by MrWillCom** [comment]
😀 谢谢！ @yzqzss 

Commit 754870a 修复了这个问题。
