### ISSUE TITLE
Waline can not be loaded onto the blog

### ISSUE THREAD

**Issue by jonie-ritie** [MrWillCom/MrWillCom.github.io#7]
This is my configuration in _config

waline:
  serverURL: https://waline-r4qhtn3is-jonie-ritie.vercel.app
  lang: zh-cn
  placeholder: 要文明评论哦, 不然会被打屁屁
  meta: [nick,mail,link]
  requiredFields: [nick]
  avatar: robohash
  avatarCDN: https://sdn.geekzu.org/avatar/
  pageSize: 10
  wordLimit: 0
  visitor: false
  dark: auto
  copyright: false

**Comment by MrWillCom** [comment]
_Fixed in https://github.com/MrWillCom/hexo-theme-cupertino/issues/16._
